### ISSUE TITLE
ConcurrentModificationException crash (unable to reproduce), Nexus 5x

### ISSUE THREAD

**Issue by gtomek** [R3PI/Defrag#24]
Caused by java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:831)
       at com.solera.defrag.ViewStack.setTraversingState(SourceFile:231)
       at com.solera.defrag.ViewStack.access$100(SourceFile:51)
       at com.solera.defrag.ViewStack$4.onMeasured(SourceFile:305)
       at com.solera.defrag.ViewUtils$1.onPreDraw(SourceFile:57)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2201)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
       at android.view.Choreographer.doCallbacks(Choreographer.java:683)
       at android.view.Choreographer.doFrame(Choreographer.java:619)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by tomjhall** [comment]
So sounds like calls to add/remove listener are not on the main thread. All calls for ViewStack should be on the main thread (we could put in a checkOnUiThread() sort of method here, potentially).

**Comment by neilmarietta** [comment]
Resolved by https://github.com/R3PI/Defrag/commit/f9447673a4b5951b2395c09dc69cdd1d8623fc2c.

**Comment by tomjhall** [comment]
Fixed in release 1.0.0
