### ISSUE TITLE
State restore crash BadParcelableException when unmarshalling (v1.1.1)

### ISSUE THREAD

**Issue by gtomek** [R3PI/Defrag#40]
Could be relatively easily reproduced with Developer option "Don't keep activities" enabled and switching the app to background

```
Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.v7.widget.RecyclerView$SavedState
       at android.os.Parcel.readParcelableCreator(Parcel.java:2536)
       at android.os.Parcel.readParcelable(Parcel.java:2462)
       at android.os.Parcel.readValue(Parcel.java:2365)
       at android.os.Parcel.readSparseArrayInternal(Parcel.java:2813)
       at android.os.Parcel.readSparseArray(Parcel.java:2068)
       at com.solera.defrag.AutoValue_ViewStack_SaveStateEntry$1.createFromParcel(AutoValue_ViewStack_SaveStateEntry.java:17)
       at com.solera.defrag.AutoValue_ViewStack_SaveStateEntry$1.createFromParcel(AutoValue_ViewStack_SaveStateEntry.java:11)
       at android.os.Parcel.readParcelable(Parcel.java:2471)
       at android.os.Parcel.readValue(Parcel.java:2365)
       at android.os.Parcel.readListInternal(Parcel.java:2793)
       at android.os.Parcel.readArrayList(Parcel.java:2036)
       at com.solera.defrag.AutoValue_ViewStack_SaveState$1.createFromParcel(AutoValue_ViewStack_SaveState.java:15)
       at com.solera.defrag.AutoValue_ViewStack_SaveState$1.createFromParcel(AutoValue_ViewStack_SaveState.java:10)
       at android.os.Parcel.readParcelable(Parcel.java:2471)
       at android.os.Parcel.readValue(Parcel.java:2365)
       at android.os.Parcel.readSparseArrayInternal(Parcel.java:2813)
       at android.os.Parcel.readSparseArray(Parcel.java:2068)
       at android.os.Parcel.readValue(Parcel.java:2422)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
       at android.os.BaseBundle.unparcel(BaseBundle.java:269)
       at android.os.Bundle.getSparseParcelableArray(Bundle.java:910)
       at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2104)
       at android.app.Activity.onRestoreInstanceState(Activity.java:1047)
       at android.app.Activity.performRestoreInstanceState(Activity.java:1002)
       at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1174)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2622)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2710)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6088)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by tomjhall** [comment]
Fixed in version 1.1.2
