### ISSUE TITLE
Crash in on restore when ViewStack parameter contains a Serializable object

### ISSUE THREAD

**Issue by REggar** [R3PI/Defrag#45]
I am getting the following crash when restoring if the ViewStack contains parameters with a Serializable object.

```
Process: com.solera.defragsample, PID: 10308
java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.solera.defragsample.BreakdownPresenter$Test)
    at android.os.Parcel.readSerializable(Parcel.java:2630)
    at android.os.Parcel.readValue(Parcel.java:2416)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
    at android.os.BaseBundle.unparcel(BaseBundle.java:269)
    at android.os.BaseBundle.getInt(BaseBundle.java:854)
    at com.solera.defragsample.BreakdownPresenter.onTakeView(BreakdownPresenter.java:44)
    at com.solera.defragsample.Presenter.takeView(Presenter.java:40)
    at com.solera.defragsample.BreakdownView.onAttachedToWindow(BreakdownView.java:53)
    at android.view.View.dispatchAttachedToWindow(View.java:15509)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2916)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1526)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
    at android.view.Choreographer.doCallbacks(Choreographer.java:686)
    at android.view.Choreographer.doFrame(Choreographer.java:621)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
 Caused by: java.lang.ClassNotFoundException: com.solera.defragsample.BreakdownPresenter$Test
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:400)
    at android.os.Parcel$2.resolveClass(Parcel.java:2616)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1772)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    at android.os.Parcel.readSerializable(Parcel.java:2624)
    at android.os.Parcel.readValue(Parcel.java:2416) 
    at android.os.Parcel.readArrayMapInternal(Parcel.java:2732) 
    at android.os.BaseBundle.unparcel(BaseBundle.java:269) 
    at android.os.BaseBundle.getInt(BaseBundle.java:854) 
    at com.solera.defragsample.BreakdownPresenter.onTakeView(BreakdownPresenter.java:44) 
    at com.solera.defragsample.Presenter.takeView(Presenter.java:40) 
    at com.solera.defragsample.BreakdownView.onAttachedToWindow(BreakdownView.java:53) 
    at android.view.View.dispatchAttachedToWindow(View.java:15509) 
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2916) 
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923) 
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923) 
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923) 
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923) 
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923) 
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923) 
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1526) 
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254) 
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337) 
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874) 
    at android.view.Choreographer.doCallbacks(Choreographer.java:686) 
    at android.view.Choreographer.doFrame(Choreographer.java:621) 
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860) 
    at android.os.Handler.handleCallback(Handler.java:751) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:6119) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
 Caused by: java.lang.ClassNotFoundException: com.solera.defragsample.BreakdownPresenter$Test
    at java.lang.Class.classForName(Native Method)
    at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
    at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at java.lang.Class.classForName(Native Method) 
    at java.lang.Class.forName(Class.java:400) 
    at android.os.Parcel$2.resolveClass(Parcel.java:2616) 
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613) 
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518) 
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1772) 
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) 
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373) 
    at android.os.Parcel.readSerializable(Parcel.java:2624) 
    at android.os.Parcel.readValue(Parcel.java:2416) 
    at android.os.Parcel.readArrayMapInternal(Parcel.java:2732) 
    at android.os.BaseBundle.unparcel(BaseBundle.java:269) 
    at android.os.BaseBundle.getInt(BaseBundle.java:854) 
    at com.solera.defragsample.BreakdownPresenter.onTakeView(BreakdownPresenter.java:44) 
    at com.solera.defragsample.Presenter.takeView(Presenter.java:40) 
    at com.solera.defragsample.BreakdownView.onAttachedToWindow(BreakdownView.java:53) 
    at android.view.View.dispatchAttachedToWindow(View.java:15509) 
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2916) 
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923) 
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923) 
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923) 
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923) 
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923) 
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923) 
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1526) 
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254) 
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337) 
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874) 
    at android.view.Choreographer.doCallbacks(Choreographer.java:686) 
    at android.view.Choreographer.doFrame(Choreographer.java:621) 
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860) 
    at android.os.Handler.handleCallback(Handler.java:751) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:6119) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
 Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by tomjhall** [comment]
Have you got some sample code for this? It might be good to put this in test.

**Comment by tomjhall** [comment]
Change is now in release 1.1.3.
